### ISSUE TITLE
License

### ISSUE THREAD

**Issue by privatezero** [ablwr/osbridge2017#1]
I propose BSD license cuz it is west coast

**Comment by ablwr** [comment]
+1 MIT, reveal.js source is also licensed under MIT

**Comment by ablwr** [comment]
So the code itself would be MIT, although if we are speaking of content, it is more appropriate to use a CC license. CC0!

**Comment by privatezero** [comment]
I want to troll, but I got nothing. I propose this issue be closed.

**Comment by ablwr** [comment]
I propose YOU close it!

**Comment by privatezero** [comment]
The sage acts by doing nothing.

When nothing is done, nothing is left undone.
